### ISSUE TITLE
Strange text box appeared when searching

### ISSUE THREAD

**Issue by JessicaXLou** [todo-name/TODO-NAME#30] opened 2019-06-11 21:44 UTC
![image](https://user-images.githubusercontent.com/32353106/59309028-5d7c9580-8c57-11e9-94e7-c63fe0863cd2.png)
After I searched something, a textbook appeared with an imgur link in the bottom left corner. It is an editable text box

**Comment by s711258w** [comment] 2019-06-12 00:27
Fixed, duplicate of issue #16

**Closed by s711258w** 2019-06-12 00:27 UTC
Labels: duplicate
