### ISSUE TITLE
Likes Feature

### ISSUE THREAD

**Issue by yiranni** [todo-name/TODO-NAME#13] opened 2019-06-11 05:21 UTC
- The number of likes is always messed up when you click it multiple times. Some examples provided as following: 
- The number of likes turns to -1 when unlike it.
![image](https://user-images.githubusercontent.com/32496771/59245742-cec43600-8bce-11e9-87ca-d240594d4602.png)
![image](https://user-images.githubusercontent.com/32496771/59245756-dedc1580-8bce-11e9-9c44-daea61377893.png)

- The number of likes is negative, which is unlikely to happen in the real world.
![image](https://user-images.githubusercontent.com/32496771/59245700-b0f6d100-8bce-11e9-8c80-4bd381c0e07f.png)

**Comment by Jimmt** [comment] 2019-06-11 06:18
Duplicate of #1 and #4

**Closed by Jimmt** 2019-06-11 06:18 UTC
