### ISSUE TITLE
No restriction for Title and Description

### ISSUE THREAD

**Issue by rheaxychen** [todo-name/TODO-NAME#12] opened 2019-06-11 04:18 UTC
![image](https://user-images.githubusercontent.com/24926110/59243527-4d1bda80-8bc5-11e9-8a70-8308c237bb3c.png)
You can input an infinite long Title and description and the card are not rendering correctly.

**Comment by Jimmt** [comment] 2019-06-11 21:33
Title cap of 150 characters and description cap of 500 characters are working correctly, as shown in the first card on the left. Card not rendering correctly duplicate of #17 (now fixed).

**Closed by Jimmt** 2019-06-11 21:33 UTC
